# Generated by Django 5.2.10 on 2026-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicprofile_latitude_clinicprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='diseases_treated',
            field=models.TextField(blank=True, help_text='Comma-separated list of diseases treated, e.g., HIV, TB'),
        ),
    ]
