# Generated by Django 5.1.7 on 2026-02-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinicprofile_diseases_treated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicTransferRequest',
        ),
    ]
