# Generated by Django 5.1.7 on 2026-02-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_delete_clinictransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this clinic is active'),
        ),
    ]
