# Generated by Django 5.1.7 on 2026-02-01 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the disease')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this disease is available for selection')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='diseases_treated',
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='diseases_treated',
            field=models.ManyToManyField(blank=True, help_text='Diseases treated by this clinic', to='clinic.disease'),
        ),
    ]
