# Generated by Django 5.1.7 on 2026-02-01 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        ('patient', '0004_treatmentrecord_disease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccess',
            name='emergency_contacts_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='emergency_type',
            field=models.CharField(choices=[('medical', 'Medical Emergency'), ('mental_health', 'Mental Health Crisis'), ('violence', 'Violence/Domestic Abuse'), ('overdose', 'Drug Overdose'), ('suicide', 'Suicidal Thoughts'), ('other', 'Other')], default='medical', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('patient_triggered', 'Patient Triggered'), ('clinic_detected', 'Clinic Detected'), ('system_auto', 'System Auto-Alert')], max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True)),
                ('alert_message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
