# Generated by Django 5.1.7 on 2026-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencyaccess_emergency_contacts_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyaccess',
            name='emergency_type',
            field=models.CharField(choices=[('medical', 'Medical Emergency'), ('violence', 'Violence/Domestic Abuse'), ('overdose', 'Drug Overdose'), ('suicide', 'Suicidal Thoughts'), ('other', 'Other')], default='medical', max_length=50),
        ),
    ]
