# Generated by Django 5.2.10 on 2026-02-07 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergencyaccess_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 7, 9, 12, 11, 78204, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
