# Generated by Django 5.2.10 on 2026-02-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientprofile_current_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
