# Generated by Django 5.2.10 on 2026-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientprofile_latitude_patientprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='disease',
            field=models.CharField(default='HIV', max_length=100),
        ),
    ]
