# Generated by Django 5.1.7 on 2026-02-01 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinicprofile_diseases_treated'),
        ('patient', '0005_appointment_counsellingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('consultation_type', models.CharField(choices=[('specialist_consultation', 'Specialist Consultation'), ('emergency_care', 'Emergency Care'), ('follow_up', 'Follow-up Care'), ('diagnostic_services', 'Diagnostic Services')], default='specialist_consultation', max_length=50)),
                ('reason', models.TextField(help_text='Reason for external consultation')),
                ('current_location', models.CharField(help_text="Patient's current location", max_length=100)),
                ('stay_type', models.CharField(choices=[('temporary', 'Temporary Stay'), ('permanent', 'Permanent Stay')], default='temporary', max_length=20)),
                ('medical_data_access_granted', models.BooleanField(default=False)),
                ('access_expiry', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_consultations_parent', to='clinic.clinicprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
                ('requesting_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_consultations_requested', to='clinic.clinicprofile')),
            ],
            options={
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reason', models.TextField()),
                ('requested_data_types', models.JSONField(default=list, help_text='List of data types requested')),
                ('access_duration', models.CharField(choices=[('one_time', 'One-time Access'), ('temporary', 'Temporary Access'), ('permanent', 'Permanent Access')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('access_granted_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data_requests_parent', to='clinic.clinicprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
                ('requesting_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data_requests', to='clinic.clinicprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis', models.TextField()),
                ('medications', models.JSONField(default=list, help_text='List of medications with dosage')),
                ('instructions', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('reminder_times', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('session_type', models.CharField(choices=[('consultation', 'Video Consultation'), ('follow_up', 'Follow-up'), ('mental_health', 'Mental Health Session'), ('emergency', 'Emergency Consultation')], default='consultation', max_length=50)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('blood_pressure_systolic', 'Blood Pressure Systolic'), ('blood_pressure_diastolic', 'Blood Pressure Diastolic'), ('heart_rate', 'Heart Rate (bpm)'), ('temperature', 'Temperature (°C)'), ('blood_sugar', 'Blood Sugar (mg/dL)'), ('oxygen_saturation', 'Oxygen Saturation (%)'), ('steps', 'Daily Steps'), ('sleep_hours', 'Sleep Hours')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('device', 'Wearable Device'), ('clinic', 'Clinic Measurement')], default='manual', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'metric_type', 'recorded_at'], name='patient_hea_patient_5dea9b_idx')],
            },
        ),
    ]
