# Generated by Django 5.1.7 on 2026-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_externalconsultation_medicaldatarequest_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='mental_health_opt_in',
        ),
        migrations.AlterField(
            model_name='telemedicinesession',
            name='session_type',
            field=models.CharField(choices=[('consultation', 'Video Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency Consultation')], default='consultation', max_length=50),
        ),
    ]
