# Generated by Django 5.1.7 on 2026-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patientprofile_mental_health_opt_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this patient profile is active'),
        ),
    ]
