# Generated by Django 5.1.7 on 2026-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online/Video Call'), ('phone', 'Phone Call')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID for online consultations', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Video call link for online consultations'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_password',
            field=models.CharField(blank=True, help_text='Meeting password if required', max_length=50),
        ),
    ]
