# Generated by Django 5.1.7 on 2026-02-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_appointment_consultation_mode_appointment_meeting_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('medication_reminder', 'Medication Reminder'), ('emergency_alert', 'Emergency Alert'), ('transfer_request', 'Transfer Request'), ('general', 'General Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_read', 'created_at'], name='patient_not_patient_a19ca9_idx'), models.Index(fields=['scheduled_at'], name='patient_not_schedul_9b2d88_idx')],
            },
        ),
    ]
