# Generated by Django 5.1.7 on 2026-02-03 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('was_taken', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicationreminder')),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'unique_together': {('reminder', 'scheduled_time')},
            },
        ),
    ]
