# Generated by Django 5.1.7 on 2026-02-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_medicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingsession',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID for online sessions', max_length=100),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Video call link for online sessions'),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='meeting_password',
            field=models.CharField(blank=True, help_text='Meeting password if required', max_length=50),
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='session_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online/Video Call'), ('phone', 'Phone Call')], default='in_person', max_length=20),
        ),
    ]
