# Generated by Django 5.2.10 on 2026-02-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_counsellingsession_meeting_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
