# Generated by Django 5.2.10 on 2026-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='password_viewed',
            field=models.BooleanField(default=False, help_text='Whether the patient has viewed the appointment password'),
        ),
    ]
