# Generated by Django 5.2.10 on 2026-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_appointment_password_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('general', 'General Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('checkup', 'Regular Checkup')], default='consultation', max_length=50),
        ),
    ]
