# Generated by Django 5.2.10 on 2026-02-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='reminder_times',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='intake_times',
            field=models.JSONField(default=list, help_text="List of time strings like ['09:00', '21:00']"),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.CharField(help_text='e.g. once daily, twice daily, every 8 hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patient.prescription'),
        ),
    ]
