# Generated by Django 5.2.10 on 2026-02-08 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_remove_medicationreminder_reminder_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='intake_times',
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_time', models.TimeField()),
                ('intake_date', models.DateField(default=django.utils.timezone.now)),
                ('has_taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='patient.medicationreminder')),
            ],
            options={
                'ordering': ['intake_time'],
                'unique_together': {('reminder', 'intake_date', 'intake_time')},
            },
        ),
        migrations.DeleteModel(
            name='MedicationLog',
        ),
    ]
